name: Deploy to WordPress.org

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'SVN commit message to send; should contain release-version'
        required: true
        type: string
      plugin_name:
        description: 'code-slug name of the WordPress plugin'
        default: katalys-shop
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Package zipfile
        run: |
          cp -r trunk '${{ inputs.plugin_name }}'
          zip -qr '${{ inputs.plugin_name }}'.zip '${{ inputs.plugin_name }}'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: katalys-shop
          path: ${{ github.workspace }}/${{ inputs.plugin_name }}.zip
      - name: SVN commit
        run: |
          # Clone repo
          svn co -q 'https://plugins.svn.wordpress.org/${{ inputs.plugin_name }}' __svn
          cd __svn
          rm -rf trunk/
          cp -r ../trunk ./
          cd trunk/
          # Detect code updates
          svn add --quiet . --force
          # Remove missing files; svn-rm fails unless list is non-empty
          if svn st | grep ^!; then
            svn st | grep ^! | awk '{$1=""; print " --force \""substr($0,2)"@\"" }' | xargs svn rm --quiet
          fi
          if [[ `svn st | wc -l` -lt 1 ]]; then
            echo "No changes found!"
            svn status
            exit 1
          fi
          echo "Found the following changes:"
          svn status
          # Commit/push
          svn ci -m '${{ inputs.commit_message }}' --username '${{ secrets.WORDPRESS_USERNAME }}' --non-interactive --no-auth-cache --password '${{ secrets.WORDPRESS_PASSWORD }}'
