name: Zip Plugin

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: 1o-merchant-plugin
          dest: 1o-merchant-plugin.zip
      - uses: actions/upload-artifact@v1
        with:
          name: 1o-merchant-plugin.zip
          path: ${{ github.workspace }}/1o-merchant-plugin.zip
