name: Zip Plugin

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: papeloto/action-zip@v1
        with:
          files: katalys-shop
          recursive: false
          dest: katalys-shop.zip
      - run: |
          cp -r trunk katalys-shop
          zip -qr katalys-shop.zip katalys-shop
      - uses: actions/upload-artifact@v3
        with:
          name: katalys-shop
          path: ${{ github.workspace }}/katalys-shop.zip
