name: Zip Plugin

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: katalys-shop
          recursive: false
          dest: katalys-shop.zip
      - uses: actions/upload-artifact@v1
        with:
          name: katalys-shop
          path: ${{ github.workspace }}/katalys-shop.zip
